substitutions:
  device_name: meteo_sonda
  friendly_name: Meteo sonda
  ota_manifest_url: "https://github.com/SamuelHudec/pg-meteo/blob/main/skalka/firmware/manifest.json"
  wifi_wait_timeout: 30s
  boot_stabilize_delay: 3s
  run_duration_seconds: "120"
  run_duration: 120s
  sleep_duration: 10min

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: -10
    then:
      - delay: ${boot_stabilize_delay}
      - logger.log: "Boot: waiting for WiFi before OTA check"
      - wait_until:
          condition:
            wifi.connected:
          timeout: ${wifi_wait_timeout}
      - if:
          condition:
            wifi.connected:
          then:
            - logger.log: "Boot: WiFi connected, OTA check started"
            - update.check: fw_update
            - if:
                condition:
                  update.is_available: fw_update
                then:
                  - logger.log: "HTTP OTA: update available, starting update"
                  - update.perform: fw_update
                else:
                  - logger.log: "HTTP OTA: no update available"
          else:
            - logger.log: "Boot: WiFi timeout, OTA check skipped"
      - logger.log: "Deep sleep countdown started: active window ${run_duration}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name}_fallback"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80
  log: true

http_request:
  max_response_buffer_size: 2kb

ota:
  - platform: http_request
    id: ota_http

update:
  - platform: http_request
    id: fw_update
    name: "${friendly_name} Firmware Update"
    source: ${ota_manifest_url}
    update_interval: 0s

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi RSSI"
    update_interval: 15s

  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 15s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
    ssid:
      name: "${friendly_name} SSID"

interval:
  - interval: 15s
    then:
      - lambda: |-
          const uint32_t active_s = ${run_duration_seconds};
          const uint32_t elapsed_s = millis() / 1000U;
          if (elapsed_s < active_s) {
            ESP_LOGI("sleep", "Deep sleep in %u s", active_s - elapsed_s);
          }

deep_sleep:
  id: sleep_ctrl
  run_duration: ${run_duration}
  sleep_duration: ${sleep_duration}
